name: Docker Image Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: '2.176/Dockerfile'
            tags: [ "zyuzka/jenkins:2.176" ]
            platforms: [ 'linux/amd64', 'linux/arm64' ]

          - image: '2.305/Dockerfile'
            tags: [ "zyuzka/jenkins:2.305" ]
            platforms: [ 'linux/amd64', 'linux/arm64' ]

          - image: '2.324/Dockerfile'
            tags: [ "zyuzka/jenkins:latest", "zyuzka/jenkins:2.324" ]
            platforms: [ 'linux/amd64', 'linux/arm64' ]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platform) }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
